[[overrides]]
files = "*.sol"

[overrides.options]
printWidth = 80
tabWidth = 2
useTabs = false
singleQuote = false
bracketSpacing = true
explicitTypes = "always"
compiler = "^0.8.10"
trailingComma = "all"
semi = true
arrowParens = "avoid"
endOfLine = "lf"
